# Домашнее задание №1

In [17]:
#  0. pip install torch torchvision
import torch

In [18]:
#  1. Создайте случайный FloatTensor размера 3x4x5

a = torch.randn(3, 4, 5)
a

tensor([[[-1.9762, -0.0959, -1.0132, -1.2819, -1.1715],
         [-0.7835,  0.0247,  0.6435,  0.5136,  1.2495],
         [-1.0854, -0.2609, -0.6312, -0.1807,  1.1143],
         [ 1.3957, -0.2294,  0.7727,  1.6874,  0.3810]],

        [[-0.5336, -0.5489,  2.0657, -0.3058, -0.7819],
         [-0.4220, -0.4317,  0.0381,  0.8489,  1.2661],
         [-0.5466, -1.6403, -1.4694, -0.2654, -0.5431],
         [-0.1724, -0.2773, -0.7825, -0.2274,  0.0945]],

        [[-0.9898, -0.6397,  0.1241,  0.2813, -0.4822],
         [ 0.7722, -0.4945,  0.9146,  0.1045, -1.1921],
         [ 0.2316, -0.4384,  0.0285, -0.0410, -1.5029],
         [ 0.4042,  0.8882,  0.0603,  1.2015, -2.2282]]])

In [19]:
# 2. Выведите его форму (shape)
print('Тензор a: ', a.type(), a.shape)

Тензор a:  torch.FloatTensor torch.Size([3, 4, 5])


In [20]:
# 3. Приведите его к форме 6 X 10
a = torch.reshape(a, [6, 10])
a, a.shape

(tensor([[-1.9762, -0.0959, -1.0132, -1.2819, -1.1715, -0.7835,  0.0247,  0.6435,
           0.5136,  1.2495],
         [-1.0854, -0.2609, -0.6312, -0.1807,  1.1143,  1.3957, -0.2294,  0.7727,
           1.6874,  0.3810],
         [-0.5336, -0.5489,  2.0657, -0.3058, -0.7819, -0.4220, -0.4317,  0.0381,
           0.8489,  1.2661],
         [-0.5466, -1.6403, -1.4694, -0.2654, -0.5431, -0.1724, -0.2773, -0.7825,
          -0.2274,  0.0945],
         [-0.9898, -0.6397,  0.1241,  0.2813, -0.4822,  0.7722, -0.4945,  0.9146,
           0.1045, -1.1921],
         [ 0.2316, -0.4384,  0.0285, -0.0410, -1.5029,  0.4042,  0.8882,  0.0603,
           1.2015, -2.2282]]), torch.Size([6, 10]))

In [21]:
#  4. Создайте случайный IntTensor размера 10

b = torch.IntTensor(10)
b.type(), b

('torch.IntTensor',
 tensor([ 102625792,          0,         24,          0,         -1,   16843009,
         1668444020, 1767059048, 1529374074,  824192054], dtype=torch.int32))

In [22]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
a * b

tensor([[-2.0281e+08, -0.0000e+00, -2.4316e+01, -0.0000e+00,  1.1715e+00,
         -1.3196e+07,  4.1218e+07,  1.1371e+09,  7.8543e+08,  1.0298e+09],
        [-1.1139e+08, -0.0000e+00, -1.5148e+01, -0.0000e+00, -1.1143e+00,
          2.3507e+07, -3.8270e+08,  1.3655e+09,  2.5807e+09,  3.1399e+08],
        [-5.4759e+07, -0.0000e+00,  4.9578e+01, -0.0000e+00,  7.8191e-01,
         -7.1082e+06, -7.2032e+08,  6.7405e+07,  1.2982e+09,  1.0435e+09],
        [-5.6097e+07, -0.0000e+00, -3.5265e+01, -0.0000e+00,  5.4310e-01,
         -2.9043e+06, -4.6272e+08, -1.3828e+09, -3.4780e+08,  7.7891e+07],
        [-1.0158e+08, -0.0000e+00,  2.9774e+00,  0.0000e+00,  4.8223e-01,
          1.3006e+07, -8.2512e+08,  1.6162e+09,  1.5979e+08, -9.8251e+08],
        [ 2.3764e+07, -0.0000e+00,  6.8454e-01, -0.0000e+00,  1.5029e+00,
          6.8087e+06,  1.4819e+09,  1.0648e+08,  1.8376e+09, -1.8364e+09]])

In [23]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
a @ a.T

tensor([[10.8102,  2.4763,  2.6847,  3.3287,  0.6315, -1.0543],
        [ 2.4763,  8.5090,  0.0566,  0.2619,  2.1948, -0.2368],
        [ 2.6847,  0.0566,  8.2477, -1.2482, -0.0715, -0.9892],
        [ 3.3287,  0.2619, -1.2482,  6.2936,  0.7472,  0.5307],
        [ 0.6315,  2.1948, -0.0715,  0.7472,  4.8253,  3.4776],
        [-1.0543, -0.2368, -0.9892,  0.5307,  3.4776,  9.8712]])

In [25]:
# 7. Посчитайте производную функции y = x**3 + z - 75*t в точке (1, 0.5, 2)

x = torch.tensor(1.0, requires_grad = True) 
z = torch.tensor(0.5, requires_grad = True) 
t = torch.tensor(2.0, requires_grad = True) 

y = x**3 + z - 75*t
print('Значение функции y в точке:', y.item())

y.backward() #считаем производную по всем переменным

print('Производная функции y по x в точке: ', x.grad.item())
print('Производная функции y по z в точке: ', z.grad.item())
print('Производная функции y по t в точке: ', t.grad.item()) #частные производные

Значение функции y в точке: -148.5
Производная функции y по x в точке:  3.0
Производная функции y по z в точке:  1.0
Производная функции y по t в точке:  -75.0


In [27]:
# 8. Создайте единичный тензор размера 5x6
e = torch.ones([5, 6])
e, e.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]), torch.Size([5, 6]))

In [28]:
# 9. Переведите его в формат numpy
e = e.numpy()
e

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)